services:
  playwright:
    build:
      context: ../..
      dockerfile: apps/desktop/Dockerfile.playwright
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/desktop/node_modules
      - /app/packages/core/node_modules
      - /app/packages/ui/node_modules
    environment:
      - CI=true
      - DISPLAY=:99.0
      - ELECTRON_DISABLE_SANDBOX=1
    command: sh -c "xvfb-run --auto-servernum --server-args='-screen 0 1280x960x24' -- pnpm --filter @vibetree/desktop exec playwright test --reporter=list"